const PLUGIN_NAME = require('./plugin');
const {
    SPECIFIED_COMMENT_WITH_TASK_ID,
    RESTRICT_UNWANTED_IMPORTS
} = require('./rules');

module.exports = {
    IGNORE: `${PLUGIN_NAME}/ignore`,
    SPECIFIED_COMMENT_WITH_TASK_ID: `${PLUGIN_NAME}/${SPECIFIED_COMMENT_WITH_TASK_ID}`,
    RESTRICT_UNWANTED_IMPORTS: `${PLUGIN_NAME}/${RESTRICT_UNWANTED_IMPORTS}`,
};
